#!/usr/bin/env node
/**
 * Converts scraped JSON animation data to firmware/src/splash_animations.h.
 *
 * Per-animation palette (up to 10 entries) is converted to RGB565. Cells in
 * each frame are palette indices (0..9). Splash module looks up colors via
 * palette[cell].
 *
 * Lattice: a JSON file may carry "size", the cells a side of every frame; without
 * it the size is the grid's row count (20 for everything claudepix makes). Each
 * frame is written as size times size bytes and the table row ends in the size.
 *
 * Usage: node convert_to_c.js [--in DIR] [--out FILE]
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const opt = (k, def) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : def; };

const IN_DIR = path.resolve(opt('--in', path.join(__dirname, 'claudepix_data')));
const OUT_FILE = path.resolve(opt('--out',
  path.join(__dirname, '..', 'firmware', 'src', 'splash_animations.h')));

const PALETTE_SIZE = 10;

// The struct every table row fills. tools/add_echo_anims.py carries the same
// text (TYPEDEF there) and puts it into a header written before the size
// field existed; keep the two identical.
const TYPEDEF = [
  '// One animation. frames holds frame_count frames of size by size cells, one',
  '// palette index per byte, back to back: frame f starts at byte f * size * size',
  '// and inside a frame the cells run row by row from the top left. size is the',
  '// lattice edge in cells; 20, 40 and 60 cut the 480 px panel into whole 24, 12',
  '// and 8 px cells. A row that leaves size out gets 0, which the renderer reads',
  '// as 20. frames is const void so the generated [frame_count][size * size]',
  '// array of any lattice goes in by name.',
  'typedef struct {',
  '    const char *name;',
  '    const char *category;',
  '    uint16_t frame_count;',
  '    const uint16_t *palette;',
  '    const void *frames;',
  '    const uint16_t *holds;',
  '    uint8_t size;',
  '} splash_anim_def_t;',
].join('\n') + '\n';

// Cells a side of an animation's frames: its "size" field, else the grid's row
// count. Every frame must be exactly that square.
function latticeOf(data) {
  const size = data.size || (data.frames[0] ? data.frames[0].grid.length : 20);
  if (!Number.isInteger(size) || size < 1 || size > 255)
    throw new Error(`${data.name}: size ${size} is not a lattice of 1 to 255 cells`);
  data.frames.forEach((f, i) => {
    if (f.grid.length !== size || f.grid.some(row => row.length !== size))
      throw new Error(`${data.name}: frame ${i} is not ${size} by ${size} cells`);
  });
  return size;
}

function safeIdent(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}

// Brand override: claudepix renders the creature body in a lighter, pinker
// terracotta (#CD7F6A) than Anthropic's brand terracotta. Remap it to the
// brand color (THEME_ACCENT, #D97757) so the splash matches the brand.
const TINT_OVERRIDE = {
  '#cd7f6a': '#d97757',
};

function hexToRgb565(hex) {
  if (!hex || hex === 'transparent') return 0x0000;  // dark bg
  const ov = TINT_OVERRIDE[hex.toLowerCase()];
  if (ov) hex = ov;
  let h = hex.replace('#', '');
  if (h.length === 3) h = h.split('').map(c => c + c).join('');
  const r = parseInt(h.substr(0, 2), 16);
  const g = parseInt(h.substr(2, 2), 16);
  const b = parseInt(h.substr(4, 2), 16);
  return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
}

function paletteToRgb565(palette) {
  const out = new Array(PALETTE_SIZE).fill(0x0000);
  for (let i = 0; i < palette.length && i < PALETTE_SIZE; i++) {
    out[i] = hexToRgb565(palette[i]);
  }
  return out;
}

function main() {
  if (!fs.existsSync(IN_DIR)) {
    console.error(`No scraped data at ${IN_DIR}. Run scrape_claudepix.js first.`);
    process.exit(1);
  }

  const indexPath = path.join(IN_DIR, '_index.json');
  if (!fs.existsSync(indexPath)) {
    console.error(`Missing ${indexPath}.`);
    process.exit(1);
  }

  const index = JSON.parse(fs.readFileSync(indexPath, 'utf8'));
  console.log(`Converting ${index.length} animations`);

  let out = '';
  out += '// ============================================================\n';
  out += '// Splash animations — generated by tools/convert_to_c.js.\n';
  out += '// Source: https://claudepix.vercel.app (20x20 pixel-art creature\n';
  out += '// animation library). Frames extracted by tools/scrape_claudepix.js\n';
  out += '// from per-animation HTML files served by the source site.\n';
  out += '// Do not edit by hand — re-run the scraper + converter to refresh.\n';
  out += '// ============================================================\n';
  out += '// Each animation carries a 10-entry RGB565 palette.\n';
  out += '// Cell values 0..9 index into palette.\n';
  out += '#pragma once\n#include <stdint.h>\n\n';

  out += `#define SPLASH_PALETTE_SIZE ${PALETTE_SIZE}\n\n`;

  out += TYPEDEF + '\n';

  const entries = [];

  for (const meta of index) {
    const ident = safeIdent(meta.filename.replace(/\.html?$/, ''));
    const dataPath = path.join(IN_DIR, meta.filename.replace(/\.html?$/, '.json'));
    const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

    const pal565 = paletteToRgb565(data.palette);
    out += `static const uint16_t splash_${ident}_palette[${PALETTE_SIZE}] = {`;
    out += pal565.map(c => `0x${c.toString(16).toUpperCase().padStart(4, '0')}`).join(',');
    out += '};\n';

    const size = latticeOf(data);
    out += `static const uint8_t splash_${ident}_frames[${data.frames.length}][${size * size}] = {\n`;
    for (const f of data.frames) {
      const flat = [];
      for (let r = 0; r < size; r++)
        for (let c = 0; c < size; c++)
          flat.push(f.grid[r][c]);
      out += '    {' + flat.join(',') + '},\n';
    }
    out += '};\n';

    out += `static const uint16_t splash_${ident}_holds[${data.frames.length}] = {`;
    out += data.frames.map(f => f.hold).join(',');
    out += '};\n\n';

    entries.push({ ident, name: data.name, category: data.category, count: data.frames.length, size });
  }

  out += `#define SPLASH_ANIM_COUNT ${entries.length}\n`;
  out += 'static const splash_anim_def_t splash_anims[SPLASH_ANIM_COUNT] = {\n';
  for (const e of entries) {
    out += `    {"${e.name}", "${e.category}", ${e.count}, splash_${e.ident}_palette, splash_${e.ident}_frames, splash_${e.ident}_holds, ${e.size}},\n`;
  }
  out += '};\n';

  fs.writeFileSync(OUT_FILE, out);
  console.log(`Wrote ${OUT_FILE} (${entries.length} animations, ${(out.length / 1024).toFixed(1)} KB)`);
}

main();
